ALTER TABLE administradores
  ADD COLUMN activo TINYINT(1) NOT NULL DEFAULT 1,
  ADD COLUMN fecha_actualizacion TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

CREATE TABLE IF NOT EXISTS bloqueos_seccion (
  seccion VARCHAR(40) NOT NULL PRIMARY KEY,
  password VARCHAR(255) NOT NULL,
  activo TINYINT(1) NOT NULL DEFAULT 1,
  actualizado_por VARCHAR(100) NULL,
  fecha_actualizacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS gastos (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  concepto VARCHAR(180) NOT NULL,
  monto DECIMAL(12,2) NOT NULL,
  frecuencia ENUM('unica','mensual','anual') NOT NULL DEFAULT 'unica',
  fecha_inicio DATE NOT NULL,
  fecha_fin DATE NULL,
  activo TINYINT(1) NOT NULL DEFAULT 1,
  creado_por VARCHAR(100) NULL,
  fecha_registro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;
